name: Build MQA Identifier Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      VCPKG_ROOT: ${{ runner.temp }}\vcpkg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: kitware/setup-cmake@v3
        with:
          cmake-version: "4.0.3"

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git "%VCPKG_ROOT%"
          pushd "%VCPKG_ROOT%"
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install flac:x64-windows
          popd

      - name: Configure with CMake (using vcpkg)
        run: |
          mkdir build
          cd build
          cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="%VCPKG_ROOT%\\scripts\\buildsystems\\vcpkg.cmake"

      - name: Build
        run: |
          cd build
          cmake --build . --config Release -- /m

      - name: Collect artifact
        run: |
          mkdir artifact
          if exist build\Release\mqa_identifier.exe (
            copy build\Release\mqa_identifier.exe artifact\mqa_identifier.exe
          ) else (
            copy build\mqa_identifier.exe artifact\mqa_identifier.exe
          )

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mqa-identifier-windows
          path: artifact\mqa_identifier.exe
