name: Build MQA_identifier Windows CLI Release

on:
  workflow_dispatch:

jobs:
  build-windows-cli:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: Install FLAC (vcpkg)
        run: |
          .\vcpkg\vcpkg.exe install libflac:x64-windows
        shell: cmd

      - name: Install FLAC (vcpkg)
        run: |
          .\vcpkg\vcpkg.exe install libflac:x64-windows
        shell: cmd

      - name: Show installed FLAC files (debug)
        run: |
          echo Installed files in vcpkg\installed\x64-windows\include
          dir /b /s vcpkg\installed\x64-windows\include\FLAC*
          echo Installed lib files in vcpkg\installed\x64-windows\lib
          dir /b /s vcpkg\installed\x64-windows\lib\*
        shell: cmd

      - name: Configure Release build (force include paths)
        run: |
          set VCPKG_DIR=%CD%\vcpkg
          set VCPKG_INST=%VCPKG_DIR%\installed\x64-windows
          cmake -S . -B build -A x64 -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_TOOLCHAIN_FILE=%VCPKG_DIR%\scripts\buildsystems\vcpkg.cmake ^
            -DFLAC_INCLUDE_DIR="%VCPKG_INST%\include" ^
            -DFLACPP_INCLUDE_DIR="%VCPKG_INST%\include" ^
            -DFLACPP_INCLUDE_DIRS="%VCPKG_INST%\include" ^
            -DFLAC++_INCLUDE_DIR="%VCPKG_INST%\include" ^
            -DFLAC++_LIBRARIES="%VCPKG_INST%\lib\FLAC++.lib" ^
            -DFLAC_LIBRARY="%VCPKG_INST%\lib\FLAC.lib" ^
            -DCMAKE_CXX_FLAGS="/I%VCPKG_INST%\include" ^
            -DCMAKE_CXX_FLAGS_RELEASE="/I%VCPKG_INST%\include" ^
            -DENABLE_QT=OFF -DQT_FOUND=OFF -DGUI=OFF
        shell: cmd

      - name: Dump CMake cache for FLAC
        run: |
          cmake -S . -B build -LA | findstr /I "FLAC"
        shell: cmd

      - name: Build Release
        run: cmake --build build --config Release -- /m
        shell: cmd

      - name: Prepare artifact folder
        run: |
          mkdir output
          if exist build\Release\MQA_identifier.exe copy build\Release\MQA_identifier.exe output\
          if exist build\MQA_identifier.exe copy build\MQA_identifier.exe output\
          for %%f in (build\Release\*.dll) do copy %%f output\  || echo no-dlls
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MQA_identifier-windows-cli
          path: output
