name: Build MQA Identifier Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "4.0.3"

      - name: Setup vcpkg and install libflac
        shell: pwsh
        env:
          VCPKG_ROOT: ${{ runner.temp }}\vcpkg
        run: |
          $vcpkgRoot = Join-Path $env:RUNNER_TEMP 'vcpkg'
          Write-Host "Cloning vcpkg to: $vcpkgRoot"
          git clone https://github.com/microsoft/vcpkg.git $vcpkgRoot
          Push-Location $vcpkgRoot
          Write-Host "Bootstrapping vcpkg (batch bootstrap)"
          & .\bootstrap-vcpkg.bat
          if ($LASTEXITCODE -ne 0) { Write-Host "bootstrap-vcpkg.bat failed with exit code $LASTEXITCODE"; exit $LASTEXITCODE }
          Write-Host "Installing libflac for triplet x64-windows (provides FLAC and FLAC++ CMake targets)"
          & .\vcpkg.exe install libflac --triplet x64-windows
          if ($LASTEXITCODE -ne 0) { Write-Host "vcpkg install libflac failed with exit code $LASTEXITCODE"; exit $LASTEXITCODE }
          Write-Host "vcpkg installed packages at: $vcpkgRoot\installed\x64-windows"
          Write-Host "Listing installed include files (top-level):"
          Get-ChildItem -Path "$vcpkgRoot\installed\x64-windows\include" -Recurse | ForEach-Object { Write-Host $_.FullName }
          Write-Host "Listing installed share directories (top-level):"
          Get-ChildItem -Path "$vcpkgRoot\installed\x64-windows\share" -Recurse | ForEach-Object { Write-Host $_.FullName }
          Pop-Location

      - name: Configure with CMake (using vcpkg toolchain) and write CMakeCache
        shell: pwsh
        env:
          VCPKG_ROOT: ${{ runner.temp }}\vcpkg
        run: |
          $vcpkgRoot = Join-Path $env:RUNNER_TEMP 'vcpkg'
          $toolchain = Join-Path $vcpkgRoot 'scripts\buildsystems\vcpkg.cmake'
          Write-Host "Using vcpkg toolchain: $toolchain"
          New-Item -ItemType Directory -Path build -Force | Out-Null
          Push-Location build
          $prefix = Join-Path $vcpkgRoot 'installed\x64-windows'
          $flacShare = Join-Path $prefix 'share\flac'
          Write-Host "CMAKE_PREFIX_PATH = $prefix"
          Write-Host "FLAC_DIR = $flacShare"
          cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="$toolchain" -DVCPKG_TARGET_TRIPLET="x64-windows" -DCMAKE_PREFIX_PATH="$prefix" -DFLAC_DIR="$flacShare"
          if ($LASTEXITCODE -ne 0) {
            Write-Host "CMake configure failed. Printing CMake output files for diagnosis (if present):"
            if (Test-Path "CMakeFiles\CMakeError.log") { Get-Content "CMakeFiles\CMakeError.log" | ForEach-Object { Write-Host $_ } }
            if (Test-Path "CMakeFiles\CMakeOutput.log") { Get-Content "CMakeFiles\CMakeOutput.log" | ForEach-Object { Write-Host $_ } }
            exit $LASTEXITCODE
          }
          Write-Host "CMake configure succeeded. Showing CMakeCache.txt excerpt for FLAC:"
          if (Test-Path "CMakeCache.txt") { Select-String -Path CMakeCache.txt -Pattern "FLAC" -CaseSensitive | ForEach-Object { Write-Host $_ } }
          Pop-Location

      - name: Diagnostic: show build files and generated project info
        shell: pwsh
        run: |
          if (Test-Path build) {
            Write-Host "Listing build folder files:"
            Get-ChildItem -Path build -Recurse -File | ForEach-Object { Write-Host $_.FullName }
            $proj = Get-ChildItem -Path build -Filter "*.vcxproj" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
            if ($proj) {
              Write-Host "Project file found: $($proj.FullName)"
              Write-Host "Searching for AdditionalIncludeDirectories in project file:"
              Select-String -Path $proj.FullName -Pattern "AdditionalIncludeDirectories" -SimpleMatch | ForEach-Object { Write-Host $_.ToString() }
            } else {
              Write-Host "No .vcxproj found yet (configure may have failed)."
            }
          } else {
            Write-Host "No build directory present."
          }

      - name: Build
        shell: pwsh
        run: |
          Push-Location build
          cmake --build . --config Release -- /m
          Pop-Location

      - name: Collect artifact
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path artifact -Force | Out-Null
          if (Test-Path "build\Release\mqa_identifier.exe") {
            Copy-Item "build\Release\mqa_identifier.exe" "artifact\mqa_identifier.exe"
          } elseif (Test-Path "build\mqa_identifier.exe") {
            Copy-Item "build\mqa_identifier.exe" "artifact\mqa_identifier.exe"
          } else {
            Write-Host "ERROR: executable not found; listing build directory for debugging:"
            Get-ChildItem -Recurse build | ForEach-Object { Write-Host $_.FullName }
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mqa-identifier-windows
          path: artifact\mqa_identifier.exe
