name: Build MQA Identifier Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "4.0.3"

      - name: Setup vcpkg and install libflac
        shell: pwsh
        run: |
          $vcpkgRoot = Join-Path $env:RUNNER_TEMP 'vcpkg'
          git clone https://github.com/microsoft/vcpkg.git $vcpkgRoot
          Push-Location $vcpkgRoot
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install flac:x64-windows
          Pop-Location

      - name: Configure with CMake (using vcpkg)
        shell: pwsh
        run: |
          $vcpkgRoot = Join-Path $env:RUNNER_TEMP 'vcpkg'
          New-Item -ItemType Directory -Path build -Force | Out-Null
          Push-Location build
          cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="$vcpkgRoot\scripts\buildsystems\vcpkg.cmake"
          Pop-Location

      - name: Build
        shell: pwsh
        run: |
          Push-Location build
          cmake --build . --config Release -- /m
          Pop-Location

      - name: Collect artifact
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path artifact -Force | Out-Null
          if (Test-Path "build\Release\mqa_identifier.exe") {
            Copy-Item "build\Release\mqa_identifier.exe" "artifact\mqa_identifier.exe"
          } elseif (Test-Path "build\mqa_identifier.exe") {
            Copy-Item "build\mqa_identifier.exe" "artifact\mqa_identifier.exe"
          } else {
            Write-Host "ERROR: executable not found; listing build directory:"
            Get-ChildItem -Recurse build | ForEach-Object { Write-Host $_.FullName }
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mqa-identifier-windows
          path: artifact\mqa_identifier.exe
