name: Build MQA_identifier Windows Release

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake (already on runner, ensures PATH)
        uses: lukka/get-cmake@v4

      - name: Configure Release build
        run: cmake -S . -B build -A x64 -DCMAKE_BUILD_TYPE=Release -DENABLE_QT=OFF

      - name: Build Release
        run: cmake --build build --config Release -- /m

      - name: Collect EXE
        run: |
          mkdir output
          copy build\Release\MQA_identifier.exe output\MQA_identifier.exe
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MQA_identifier-windows
          path: output/MQA_identifier.exe
