name: Build MQA_identifier Windows CLI Release

on:
  workflow_dispatch:

jobs:
  build-windows-cli:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: Install libFLAC (static) with vcpkg
        run: |
          .\vcpkg\vcpkg.exe install libflac:x64-windows-static
        shell: cmd

      - name: Configure build (static linking)
        run: |
          set VCPKG_DIR=%CD%\vcpkg
          set VCPKG_INST=%VCPKG_DIR%\installed\x64-windows-static
          cmake -S . -B build -A x64 -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_TOOLCHAIN_FILE=%VCPKG_DIR%\scripts\buildsystems\vcpkg.cmake ^
            -DVCPKG_TARGET_TRIPLET=x64-windows-static ^
            -DENABLE_QT=OFF -DQT_FOUND=OFF -DGUI=OFF ^
            -DCMAKE_CXX_FLAGS="/I%VCPKG_INST%\include" ^
            -DCMAKE_EXE_LINKER_FLAGS="/LIBPATH:%VCPKG_INST%\lib"
        shell: cmd

      - name: Dump CMake cache for FLAC
        run: |
          cmake -S . -B build -LA | findstr /I "FLAC"
        shell: cmd

      - name: Verify vcpkg lib files (static)
        run: |
          echo "Listing vcpkg installed lib for static triplet"
          if exist vcpkg\installed\x64-windows-static\lib (
            dir /b vcpkg\installed\x64-windows-static\lib
          ) else (
            echo "vcpkg installed lib folder not found for x64-windows-static"
            dir /b vcpkg\installed
          )
        shell: cmd

      - name: Build Release
        run: cmake --build build --config Release -- /m
        shell: cmd

      - name: Find any FLAC DLLs (debug)
        run: |
          echo "search vcpkg installed bin (dynamic)"
          dir /b /s vcpkg\installed\x64-windows\bin\*FLAC*.dll 2>nul || echo none
          echo "search vcpkg installed bin (static)"
          dir /b /s vcpkg\installed\x64-windows-static\bin\*FLAC*.dll 2>nul || echo none
          echo "search repo tree"
          dir /b /s *FLAC*.dll 2>nul || echo none
        shell: cmd

      - name: Prepare artifact folder (static build)
        run: |
          mkdir output
          rem copy EXE from common locations
          if exist build\Release\MQA_identifier.exe copy build\Release\MQA_identifier.exe output\ || echo no-exe-in-build-Release
          if exist build\MQA_identifier.exe copy build\MQA_identifier.exe output\ || echo no-exe-in-build_root
          if exist MQA_identifier.exe copy MQA_identifier.exe output\ || echo no-exe-in-repo-root

          rem show what we will upload
          dir output
        shell: cmd

      - name: Upload artifact (full output)
        uses: actions/upload-artifact@v4
        with:
          name: MQA_identifier-windows-cli-full
          path: output
