name: Build MQA_identifier Windows CLI Release

on:
  workflow_dispatch:

jobs:
  build-windows-cli:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: Install libFLAC static (vcpkg)
        run: |
          .\vcpkg\vcpkg.exe install libflac:x64-windows-static
          .\vcpkg\vcpkg.exe install libogg:x64-windows-static
        shell: cmd

      - name: Clean previous CMake build (safe)
        run: |
          if exist build rmdir /s /q build
        shell: cmd
        
      - name: Configure build (static linking) with forced linker paths
        run: |
          set VCPKG_DIR=%CD%\vcpkg
          set VCPKG_INST=%VCPKG_DIR%\installed\x64-windows-static
          if exist build rmdir /s /q build
          cmake -S . -B build -A x64 -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_TOOLCHAIN_FILE=%VCPKG_DIR%\scripts\buildsystems\vcpkg.cmake ^
            -DVCPKG_TARGET_TRIPLET=x64-windows-static ^
            -DFLACPP_INCLUDE_DIR="%VCPKG_INST%\include" ^
            -DFLAC_INCLUDE_DIR="%VCPKG_INST%\include" ^
            -DFLACPP_LIBRARY="%VCPKG_INST%\lib\FLAC++.lib" ^
            -DFLACPP_LIBRARIES="%VCPKG_INST%\lib\FLAC++.lib" ^
            -DFLAC_LIBRARY="%VCPKG_INST%\lib\FLAC.lib" ^
            -DCMAKE_EXE_LINKER_FLAGS="/LIBPATH:%VCPKG_INST%\lib" ^
            -DCMAKE_SHARED_LINKER_FLAGS="/LIBPATH:%VCPKG_INST%\lib" ^
            -DCMAKE_MODULE_LINKER_FLAGS="/LIBPATH:%VCPKG_INST%\lib" ^
            -DCMAKE_CXX_FLAGS="/I%VCPKG_INST%\include" ^
            -DCMAKE_CXX_FLAGS_RELEASE="/I%VCPKG_INST%\include" ^
            -DENABLE_QT=OFF -DQT_FOUND=OFF -DGUI=OFF
        shell: cmd
        
      - name: Verify linker flags and FLAC settings
        run: |
          cmake -S . -B build -LA | findstr /I "FLAC"
          findstr /I "/LIBPATH" build\MQA_identifier.vcxproj || echo "/LIBPATH not found in vcxproj"
          findstr /I "FLAC++.lib" build\MQA_identifier.vcxproj || echo "FLAC++.lib not referenced in vcxproj"
        shell: cmd

      - name: Show vcpkg include dir (debug)
        run: |
          echo "Contents of vcpkg include (static)"
          dir /b /s vcpkg\installed\x64-windows-static\include\FLAC* || echo "not found"
        shell: cmd

      - name: Dump CMake cache for FLAC
        run: |
          cmake -S . -B build -LA | findstr /I "FLAC"
        shell: cmd

      - name: Verify vcpkg lib files (static)
        run: |
          echo "Listing vcpkg installed lib for static triplet"
          if exist vcpkg\installed\x64-windows-static\lib (
            dir /b vcpkg\installed\x64-windows-static\lib
          ) else (
            echo "vcpkg installed lib folder not found for x64-windows-static"
            dir /b vcpkg\installed
          )
        shell: cmd

      - name: Build Release (use vcpkg LIB/INCLUDE)
        run: |
          set VCPKG_INST=%CD%\vcpkg\installed\x64-windows-static
          rem prepend vcpkg lib and include to LIB and INCLUDE for MSVC linker/compiler
          set LIB=%VCPKG_INST%\lib;%LIB%
          set INCLUDE=%VCPKG_INST%\include;%INCLUDE%
          cmake --build build --config Release -- /m
        shell: cmd

      - name: Find any FLAC DLLs (debug)
        run: |
          echo "search vcpkg installed bin (dynamic)"
          dir /b /s vcpkg\installed\x64-windows\bin\*FLAC*.dll 2>nul || echo none
          echo "search vcpkg installed bin (static)"
          dir /b /s vcpkg\installed\x64-windows-static\bin\*FLAC*.dll 2>nul || echo none
          echo "search repo tree"
          dir /b /s *FLAC*.dll 2>nul || echo none
        shell: cmd

      - name: Prepare artifact folder (static build)
        run: |
          mkdir output
          rem copy EXE from common locations
          if exist build\Release\MQA_identifier.exe copy build\Release\MQA_identifier.exe output\ || echo no-exe-in-build-Release
          if exist build\MQA_identifier.exe copy build\MQA_identifier.exe output\ || echo no-exe-in-build_root
          if exist MQA_identifier.exe copy MQA_identifier.exe output\ || echo no-exe-in-repo-root

          rem show what we will upload
          dir output
        shell: cmd

      - name: Upload artifact (full output)
        uses: actions/upload-artifact@v4
        with:
          name: MQA_identifier-windows-cli-full
          path: output
